site_name: bubseek
repo_url: https://github.com/psiace/bubseek
site_url: https://psiace.github.io/bubseek
site_description: Intelligent Perception and Explainable Analytics in Collaboration ｜ Bub & seekdb Inside
site_author: Chojan Shang
edit_uri: edit/main/docs/
repo_name: psiace/bubseek
copyright: Maintained by <a href="https://psiace.com">psiace</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/bubseek"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/psiace/bubseek
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/bubseek

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
